config/routes.rb
Rails.application.routes.draw do
  resources :items 


  resources :users do
    resources :shops, only: [:new]
  end

  resources :shops, except: [:new] 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
    has_many :shops
    has_many :users, through: :shops

end

app/models/shop.rb
class Shop < ApplicationRecord
    belongs_to :item
    belongs_to :user


end

app/models/user.rb
class User < ApplicationRecord
    has_many :shops
    has_many :items, through: :shops

    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

    def index
        @items = Item.all
    end

    def show
        @item = find_me
        # @user = User.find()
    end

    def new
        @item = Item.new
        
    end

    def create
        # byebug
        item = Item.create(permission)
        redirect_to item_path(item)
    end

    def edit
        @item = find_me
    end

    def update
        find_me.update(permission)
        redirect_to item_path
    end

    def destroy
        item = find_me
        Item.delete(item)
        redirect_to items_path
    end

    private

    def find_me
        Item.find(params[:id])
    end


    # def find_user
        
    # end

    def permission
        params.require(:item).permit(:name, :category, :description, :image)
    end

end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
    
    def index 
       
        @shops = Shop.all
    end

    def show
        @shop = Shop.find(params[:id])
    end
    
    
    def new
        # byebug
        @user = User.find(params[:user_id])
        # byebug
        @shop = Shop.new
        # @items = Item.all
        # @users = User.all
    end

    def create
        # byebug
        shop = Shop.create(params.require(:shop).permit(:user_id, :item_id))
        byebug
        redirect_to user_path(shop.user_id)
        
    end

    def edit
    end

    def update
    end

    def destroy
        byebug

        shop = Shop.find_by(id: params[:id])
        Shop.delete(shop)
        redirect_to new_shop_path
    end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
        @users = User.all
    end

    def show
        @user = find_me
        @items = @user.items
        @shops = @user.shops
        
        
    end

    def new
        @user = User.new
        
    end

    def create
        # byebug
        user = User.create(permission)
        redirect_to user_path(user)
    end

    def edit
        @user = find_me
    end

    def update
        find_me.update(permission)
        redirect_to user_path
    end

    def destroy
        user = find_me
        User.delete(user)
        redirect_to items_path
    end

    private

    def find_me
        User.find(params[:id])
    end

    def permission
        params.require(:user).permit(:name, :address, :preference, :gender)
    end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/edit.html.erb
<div class="container">
    <div class="row">
        <h1>Edit item</h1>
    </div>

  <div class="row">
   <%= form_for @item do |f|%>
    <div class="col">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="col">
      <%= f.label :category %>
      <%= f.text_field :category %>
    </div>
    <div class="col">
      <%= f.label :description %>
        <%= f.text_field :description %>
    </div>
    <div class="col">
      <%= f.label :image %>
        <%= f.text_field :image %>
        <br>
        <%= f.submit%>
    </div>

    <% end %>

  </div>

    <div class="row">
        <%= button_to "new listing", new_item_path, method: :get%>
        <br>
        <%= button_to "back", item_path, method: :get %>
        <br>
        <%= button_to "delete", item_path, method: :delete%>
    </div>
    
</div>

app/views/items/index.html.erb
<div class="container">

  <div class="row tracking-in-expand">
      <h1> Item List</h1>
  </div>

  <div class="row">

    <% @items.each do |item| %>
        <div class = "col text-center bounce-in-left">
            <h3><%= link_to item.name, item %></h3>
            <ul>
                <li><%= item.description %></li>
                <li><%= item.category %></li>
            </ul>
            <img src="<%= item.image %>" alt="<%= item.name %>"> 
        </div>
        
    <% end %>

  </div>

  <div class="row">
    <%= button_to "Back To home", users_path, method: :get%>
  </div>

</div>

app/views/items/new.html.erb
<div class="container">
    <div class="row">
        <h1>NEW item</h1>
    </div>

  <div class="row tracking-in-expand">
   <%= form_for @item do |f|%>
    <div class="col">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="col">
      <%= f.label :category %>
      <%= f.text_field :category %>
    </div>
    <div class="col">
      <%= f.label :description %>
        <%= f.text_field :description %>
    </div>
    <div class="col">
      <%= f.label :image %>
        <%= f.text_field :image %>
        <br>
        <%= f.submit%>
    </div>

    <% end %>

  </div>

    <div class="row">
        <%= button_to "Show all Listing", items_path, method: :get %>
    </div>
    
</div>

app/views/items/show.html.erb
<div class="container">

    <div class="row bounce-in-left">
        <h1><%= @item.name%></h1>
    </div>

    <div class="row">
        <div class="col bounce-in-left">
            <p><%= @item.description%></p>
        </div>
        
        <div class="col bounce-in-left">
            <p><%= @item.category%></p>
        </div>
    </div>

    <div class="row fade-in">
        <img src="<%= @item.image%>" alt="<%= @item.name%>">
    </div>

    <div class="row">
       <%= button_to "edit", edit_item_path, method: :get %>
        <br>
        <%= button_to "Show all Listing", items_path, method: :get %>
        <br>
        <%= button_to "new listing", new_item_path, method: :get%>
    </div>
    
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FUCCI</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


     <%= stylesheet_link_tag "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" %>
     <link href="https://fonts.googleapis.com/css?family=Notable&display=swap" rel="stylesheet">
     <link href="https://fonts.googleapis.com/css?family=Mansalva&display=swap" rel="stylesheet">
     <link href="https://fonts.googleapis.com/css?family=Merriweather&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


    <div class="color-change-4x">
      <%= yield %>
    </div>
    

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shops/new.html.erb
<%= form_for @shop do |f|%>
    <%= f.hidden_field :user_id, :value => @user.id%>

    <%= f.label :item_id%>
    <%= f.collection_select(:item_id, Item.all, :id, :name)%>

    <%= f.submit "Put in my bag"%>
<%end%>

app/views/users/edit.html.erb
<h2>Edit My Account</h2>

<%= form_for @user do |f|%>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :address %>
    <%= f.text_field :address %>

    <%= f.label "style Preferance" %>
    <%= f.text_field :preference %>

    <%= f.label :gender %>
    <%= f.text_field :gender %>

    <%= f.submit%>

<% end %>

<%= button_to "back", user_path, method: :get %>

app/views/users/index.html.erb
<h1> Are you a returning user</h1>


<h2>Register</h2>
<%= button_to "sign up", new_user_path, method: :get %>

app/views/users/new.html.erb
<h1>new user</h1>

<%= form_for @user do |f|%>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :address %>
    <%= f.text_field :address %>

    <%= f.label "style Preferance" %>
    <%= f.text_field :preference %>

    <%= f.label :gender %>
    <%= f.text_field :gender %>

    <%= f.submit%>

<% end %>

app/views/users/show.html.erb
<div class="container">

    <div class="row bounce-in-left">
        <h1>Welcome <%= @user.name %></h1>
    </div>

    <div>
        <h3> Shopping List</h3>
    </div>

  <div class="row fade-in">

   <% @user.items.each do |item|%>

    <div class="col">
      <p><%= link_to item.name, item_path(item) %></p>
      <img src="<%= item.image %>" alt="">
    </div>
    
    <% end %>

  </div>

    <div class="row">
       <%= button_to "Edit my account", edit_user_path, method: :get %>
        <br>
        <%= button_to "See listings", items_path, method: :get %>
        <br>
        <%= button_to "Buy", new_user_shop_path(@user), method: :get%>
    </div>
    
</div>